/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as blocklistSol from "./Blocklist.sol";
export * as custodianSol from "./Custodian.sol";
export { USVP__factory } from "./USVP__factory";
