/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as blocklistSol from "./Blocklist.sol";
export type { blocklistSol };
import type * as custodianSol from "./Custodian.sol";
export type { custodianSol };
export type { USVP } from "./USVP";
